name: congthanhng
description: A Community Battle game in Github profile.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  github: ^9.9.0
