# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Run Battle"

on:
  issues:
    types: [opened]

jobs:
  action:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'battle|')
    steps:
      - name: Checkout build branch
        uses: actions/checkout@v3
        with:
          ref: build
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: run-game
        run: dart run lib/main.dart "${{ github.event.issue.title }}" "${{ github.event.issue.user.login }}"
      - name: Push change commit to root branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply run-game changes on main
          branch: main
          file_pattern: 'README.md'
          skip_dirty_check: true
          push_options: '--force'

      - name: Push change commit to build branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply run-game changes on build
          branch: build
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: "Hi @${{ github.event.issue.user.login }}! Your move Success - Auto Close Issue"
      - name: The job has failed
        if: ${{ failure() }}
        uses: peter-evans/close-issue@v2
        with:
          comment: "Hi @${{ github.event.issue.user.login }}! Your move Failure - Auto Close Issue"