# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Run Battle"

on:
  issues:
    types: [opened]

jobs:
  action:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'battle|')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dart
        uses: dart-lang/setup-dart@v1
      - name: get dependencies
        run: dart pub get
      - name: run-game
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.repository }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          USER_PLAYER: ${{ github.event.issue.user.login }}
        run: dart run lib/main.dart
      - name: Push change commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply run-game changes
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: "Hi @${{ github.event.issue.user.login }}! Your move is successful. The Issue will be closed."
      - name: The job has failed
        if: ${{ failure() }}
        uses: peter-evans/close-issue@v2
        with:
          comment: "Hi @${{ github.event.issue.user.login }}! Your move failed. Please try again. The Issue will be closed."